### ISSUE TITLE
Bug: Country Box => Continent Title

### ISSUE THREAD

**Issue by Canoir** [rezamehdipour/covid19#1]
When a Country is set to WorldWide, the Continent is NAN!  Even if this NAN is not the not-a-number and it is the not-a-nation, then you should provide a better title.
![image](https://user-images.githubusercontent.com/24988065/168503586-c082cbcf-24b3-4e64-b93c-ef39f8f9fd84.png)

**Comment by rezamehdipour-old** [comment]
Thanks for your attention. Continent title removed for Worldwide statistics.
[Related Commit](https://github.com/rezamehdipour/covid19/commit/03cf6087ae196ab635e1688fe414d8fdde0d1d85)
